import NavAuthBar from "@/components/auth/NavAuthBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <div className="w-full">
        <div className="w-[50%] mx-auto">
            <NavAuthBar />
        </div>
        {children}
     </div>
  );
}
